FROM openjdk:11-jre

# Copy controller, agent files, and the script
COPY ngrinder-controller-3.5.8.war /app/ngrinder-controller-3.5.8.war
COPY ngrinder-agent-3.5.8-localhost.tar /app/
COPY start_both.sh /app/start_both.sh

WORKDIR /app

# Extract agent tar
RUN tar -xvf ngrinder-agent-3.5.8-localhost.tar

# Make the script executable
RUN chmod +x /app/start_both.sh

# Use the script to run both processes
CMD ["/app/start_both.sh"]
